import Nav from "@/Components/Footer";
import Head from "next/head";
import Logo from "public/Cyber_Automotive_LogoV5.png";
import { Disclosure, Menu, Transition } from "@headlessui/react";
import { FaBars } from "react-icons/fa";
import react, { Fragment } from "react";
import Image from "next/image";
import Link from "next/link";
import Footer from "@/Components/Footer";
import React, { useState, useEffect } from "react";



export default function Vehicles() {

  function newElement(element) {
    return document.createElement(element);
  }
  
  function setFeatured(target) {
    let vehicleRow = document.getElementById("cars");
  
    let cardContainer = newElement("div");
    let card = newElement("div");
    let vehiclePhoto = newElement("div");
    let vehiclePrice = newElement("div");
    let vehicleInfo = newElement("div");
  
    vehicleRow.appendChild(cardContainer);
    cardContainer.setAttribute("class", "md:w-1/3 2xl:w-1/3 mx-auto my-7");
    cardContainer.setAttribute("id", "car-img");
    cardContainer.appendChild(card);
  
    card.setAttribute("class", "border-2 border-rose shadow-glow shadow-rose bg-oxford-blue text-robin-egg-blue");
    card.appendChild(vehiclePhoto);
    card.appendChild(vehiclePrice);
    card.appendChild(vehicleInfo);
    vehiclePhoto.setAttribute("class", "vehicle-photo");
    vehiclePrice.setAttribute("class", "bg-indigo-dye");
    vehicleInfo.setAttribute("class", "vehicle-info");
  
    //putting in info
    let photoLink = newElement("a");
    let vehicleImage = newElement("img");
    let special = newElement("span");
    let infoLink = newElement("a");
    let title = newElement("h2");
    let miles = newElement("p");
  
    vehiclePhoto.appendChild(photoLink);
    photoLink.setAttribute(
      "title",
      `Used ${target.productionYear} ${target.make} ${target.model}`
    );
    photoLink.setAttribute("href", `./vehicle.html#${target.make} ${target.model}`);
    photoLink.appendChild(vehicleImage);
  
    vehicleImage.setAttribute("class", "");
    vehicleImage.setAttribute("src", `${target.images[0]}`);
    vehicleImage.setAttribute(
      "alt",
      `Used ${target.productionYear} ${target.make} ${target.model} for sale`
    );
    vehicleImage.setAttribute("loading", "lazy");
  
    vehiclePrice.appendChild(special);
    special.setAttribute("class", "");
    vehiclePrice.innerHTML = `$${target.price} <span class="">$${target.originalPrice}</span>`;
    special.innerHTML = `${target.originalPrice}`;
  
    vehicleInfo.appendChild(infoLink);
    infoLink.setAttribute("href", `./vehicle.html#${target.make} ${target.model}`);
    infoLink.appendChild(title);
    title.setAttribute("class", "");
    title.innerHTML = `${target.productionYear} ${target.make} ${target.model}`;
    vehicleInfo.appendChild(miles);
    miles.setAttribute("class", "");
    miles.innerHTML = `${target.mileage} miles`;
  }

  const [data, setData] = useState([{}])
useEffect(() => {
  fetch("/CarInventory.json")
    .then((response) => response.json())
    .then((data) => {
      for (var carName in data) {
        setFeatured(data[carName]);
      }
    });
})

  return (
    <>
      <Head>
        <title>Cyber Automotive Rides</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Start of Nav */}
      <nav className=" bg-oxford-blue overflow-hidden">
        <div>
          <Image src={Logo} className=" w-2/3 max-w-lg mx-auto" />
        </div>
        <div
          id="nav"
          className=" hidden xl:flex xl:flex-row sticky text-center py-2 overflow-hidden shadow-rose pb-7"
        >
          <div className=" mx-auto">
            <Link href="/" className="cybr-btn w-2 m-auto cybr-btn-default">
              Home<span>_</span>
              <span className="cybr-btn__glitch">Home_</span>
            </Link>
          </div>
          <div className=" mx-auto">
            <Link
              href="/vehicles"
              className="cybr-btn w-2 m-auto cybr-btn-active"
            >
              Vehicles<span>_</span>
              <span className="cybr-btn__glitch">Vehicles_</span>
            </Link>
          </div>
          <div className=" mx-auto">
            <Link
              href="/financing"
              className="cybr-btn w-2 m-auto cybr-btn-default"
            >
              Financing<span>_</span>
              <span className="cybr-btn__glitch">Financing_</span>
            </Link>
          </div>
          <div className=" mx-auto">
            <Link
              href="/company"
              className="cybr-btn w-2 m-auto cybr-btn-default"
            >
              Company<span>_</span>
              <span className="cybr-btn__glitch">Company_</span>
            </Link>
          </div>
        </div>
        <Menu>
          <Menu.Button className="absolute right-5 top-14 xs:right-9 xs:top-20 sm:top-36 sm:right-14 lg:right-32">
            <FaBars className=" text-gray-200 cursor-pointer  m-auto text-3xl xs:text-4xl sm:text-5xl xl:hidden" />
          </Menu.Button>
          <Transition
            as={Fragment}
            enter="transition ease-out duration-200"
            enterFrom="transform opacity-0 scale-205"
            enterTo="transform opacity-100 scale-100"
            leave="transition ease-in duration-75"
            leaveFrom="transform opacity-100 scale-200"
            leaveTo="transform opacity-0 scale-205"
          >
            <Menu.Items
              id="dropdownNav"
              className=" bg-oxford-blue w-full absolute xl:hidden"
            >
              <ul className=" font-oxta">
                <Menu.Item>
                  <li className="text-center py-7">
                    <Link
                      href="/"
                      className="cybr-btn w-2 m-auto cybr-btn-default"
                    >
                      Home<span>_</span>
                      <span className="cybr-btn__glitch">Home_</span>
                    </Link>
                  </li>
                </Menu.Item>
                <Menu.Item>
                  <li className="text-center py-7">
                    <Link
                      className="cybr-btn w-2 m-auto cybr-btn-active"
                      href="/vehicles"
                    >
                      Vehicles<span>_</span>
                      <span className="cybr-btn__glitch">Vehicles_</span>
                    </Link>
                  </li>
                </Menu.Item>
                <Menu.Item>
                  <li className="text-center py-7">
                    <Link
                      href="/financing"
                      className="cybr-btn w-2 m-auto cybr-btn-default"
                    >
                      Financing<span>_</span>
                      <span className="cybr-btn__glitch">Financing_</span>
                    </Link>
                  </li>
                </Menu.Item>
                <Menu.Item>
                  <li className="text-center py-7">
                    <Link
                      href="/company"
                      className="cybr-btn w-2 m-auto cybr-btn-default"
                    >
                      Company<span>_</span>
                      <span className="cybr-btn__glitch">Company_</span>
                    </Link>
                  </li>
                </Menu.Item>
              </ul>
            </Menu.Items>
          </Transition>
        </Menu>
      </nav>
      <main className=" bg-gradient-to-b from-indigo-dye to-oxford-blue py-10">
        <div className=" w-11/12 block text-center mx-auto mt-10 mb-20 bg-oxford-blue p-7 border-rose border-4 rounded-sm text-rose font-avalon text-3xl max-w-lg">
          <h1>INVENTORY</h1>
        </div>
        <div className="xl:flex">
        {/* Start of Filter */}
        <div id="filter" className="mx-auto border-2 border-robin-egg-blue w-10/12 xl:w-1/6 xl:ml-5 shadow-glow shadow-robin-egg-blue bg-oxford-blue p-5 ">
        {/* Filter Make */}
        <div>
          <div className="text-rose w-2/3 mx-auto text-2xl font-oxta border-b-2 border-rose max-w-sm">
            <h2 className="">MAKE</h2>
          </div>
          <div className="w-2/3 mx-auto">
          <select
            name=""
            id=""
            className=" max-w-sm mt-5 mb-7 w-full mx-auto block h-14 bg-oxford-blue text-robin-egg-blue appearance-none font-oxta pl-4 border-robin-egg-blue border-2 shadow-glow shadow-robin-egg-blue focus:outline-none focus:text-rose focus:border-rose focus:shadow-rose"
          >
            <option value="All">All</option>
          </select>
          </div>
        </div>
        {/* Filter Model */}
        <div>
          <div className="text-rose w-2/3 mx-auto text-2xl font-oxta border-b-2 border-rose max-w-sm">
            <h2 className="">MODEL</h2>
          </div>
          <div className="w-2/3 mx-auto">
          <select
            name=""
            id=""
            className=" max-w-sm mt-5 mb-7 w-full mx-auto block h-14 bg-oxford-blue text-robin-egg-blue appearance-none font-oxta pl-4 border-robin-egg-blue border-2 shadow-glow shadow-robin-egg-blue focus:outline-none focus:text-rose focus:border-rose focus:shadow-rose"
          >
            <option value="All">All</option>
          </select>
          </div>
        </div>
        {/* Filter Color */}
        <div>
          <div className="text-rose w-2/3 mx-auto text-2xl font-oxta border-b-2 border-rose max-w-sm">
            <h2 className="">COLOR</h2>
          </div>
          <div className="w-2/3 mx-auto">
          <select
            name=""
            id=""
            className=" max-w-sm mt-5 mb-7 w-full mx-auto block h-14 bg-oxford-blue text-robin-egg-blue appearance-none font-oxta pl-4 border-robin-egg-blue border-2 shadow-glow shadow-robin-egg-blue focus:outline-none focus:text-rose focus:border-rose focus:shadow-rose"
          >
            <option value="All">All</option>
          </select>
          </div>
        </div>
        {/* Filter Price */}
        <div>
          <div className="text-rose w-2/3 mx-auto text-2xl font-oxta border-b-2 border-rose max-w-sm">
            <h2 className="">PRICE</h2>
          </div>
          <div className="w-2/3 mx-auto">
          <select
            name=""
            id=""
            className=" max-w-sm mt-5 mb-7 w-full mx-auto block h-14 bg-oxford-blue text-robin-egg-blue appearance-none font-oxta pl-4 border-robin-egg-blue border-2 shadow-glow shadow-robin-egg-blue focus:outline-none focus:text-rose focus:border-rose focus:shadow-rose"
          >
            <option value="All">All</option>
          </select>
          </div>
        </div>
        {/* Filter Mileage */}
        <div>
          <div className="text-rose w-2/3 mx-auto text-2xl font-oxta border-b-2 border-rose max-w-sm">
            <h2 className="">MILEAGE</h2>
          </div>
          <div className="w-2/3 mx-auto">
          <select
            name=""
            id=""
            className=" max-w-sm mt-5 mb-7 w-full mx-auto block h-14 bg-oxford-blue text-robin-egg-blue appearance-none font-oxta pl-4 border-robin-egg-blue border-2 shadow-glow shadow-robin-egg-blue focus:outline-none focus:text-rose focus:border-rose focus:shadow-rose"
          >
            <option value="All">All</option>
          </select>
          </div>
        </div>
        </div>
        {/* Start of Cars */}
        <div id="cars" className=" w-2/3 mx-auto flex flex-wrap">

        </div>
        </div>
      </main>
      <Footer />
    </>
  );
  }
